#!/bin/bash -p
set -euo pipefail

if [[ $- != *p* ]]; then
  builtin printf '%s\n' 'ERROR: open scripts/field/install_one_time_capture.command directly; imported Bash startup state must remain disabled.' >&2
  exit 2
fi

set +x
PATH="/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH
unset BASH_ENV ENV CDPATH GLOBIGNORE XCODE_XCCONFIG_FILE OTHER_SWIFT_FLAGS SWIFT_ACTIVE_COMPILATION_CONDITIONS || true

ROOT="$(cd "$(/usr/bin/dirname "$0")/../.." && /bin/pwd -P)"
cd "$ROOT"
umask 077

say() { builtin printf '\n==> %s\n' "$*"; }
die() { builtin printf '\nERROR: %s\n' "$*" >&2; exit 1; }

[[ "$(/usr/bin/uname -s)" == "Darwin" ]] || die "Run this on the intended field Mac."
[[ -x /usr/bin/python3 ]] || die "System Python 3 is required."
[[ -x /usr/bin/shasum ]] || die "System shasum is required."
[[ -x /usr/bin/git ]] || die "System Git is required for immutable nested-tool custody."

# PRE-INSTALL ONLY.
#
# This command authenticates and cross-binds the stable retained-install subjects that already
# exist before the app is launched. It deliberately cannot accept the current-procedure signed
# authorization envelope here: that envelope binds a fresh process-local challenge generated by
# the installed running app, so requiring it pre-install would create an impossible chronology
# cycle. This migration remains non-authorizing and has no device/install primitive below.
RETAINED_INSTALL_CONTRACT_STATUS="stable-subjects-validated-await-app-attempt-authority"

validate_retained_input() {
  local label="$1"
  local input_path="$2"
  local expected_sha256="$3"
  local access_policy="$4"
  local maximum_bytes="$5"

  [[ "$expected_sha256" =~ ^[0-9A-Fa-f]{64}$ ]] || die "$label expected SHA-256 must be 64 hex characters."
  expected_sha256="$(printf '%s' "$expected_sha256" | /usr/bin/tr '[:upper:]' '[:lower:]')"

  /usr/bin/env -i \
    PATH=/usr/bin:/bin \
    LC_ALL=C \
    /usr/bin/python3 -I -B - \
      "$label" "$input_path" "$expected_sha256" "$access_policy" "$maximum_bytes" <<'PY'
import hashlib
import hmac
import os
import stat
import sys
from pathlib import PurePath

label, raw_path, expected, access_policy, maximum_raw = sys.argv[1:]
if not raw_path.startswith("/") or "\x00" in raw_path:
    raise SystemExit(2)
path = PurePath(raw_path)
if path.parts[0] != "/" or any(part in {"", ".", ".."} for part in path.parts[1:]):
    raise SystemExit(3)
if access_policy not in {"public", "private"}:
    raise SystemExit(4)
try:
    maximum = int(maximum_raw, 10)
except ValueError:
    raise SystemExit(5)
if maximum <= 0:
    raise SystemExit(6)

no_follow = getattr(os, "O_NOFOLLOW", None)
if no_follow is None:
    raise SystemExit(7)
directory_fd = os.open("/", os.O_RDONLY | os.O_DIRECTORY)
try:
    for component in path.parts[1:-1]:
        next_fd = os.open(
            component,
            os.O_RDONLY | os.O_DIRECTORY | no_follow,
            dir_fd=directory_fd,
        )
        os.close(directory_fd)
        directory_fd = next_fd
    descriptor = os.open(path.parts[-1], os.O_RDONLY | no_follow, dir_fd=directory_fd)
finally:
    os.close(directory_fd)

try:
    before = os.fstat(descriptor)
    if not stat.S_ISREG(before.st_mode) or before.st_nlink != 1:
        raise SystemExit(8)
    if hasattr(os, "geteuid") and before.st_uid != os.geteuid():
        raise SystemExit(9)
    forbidden_mode = 0o077 if access_policy == "private" else 0o022
    if stat.S_IMODE(before.st_mode) & forbidden_mode:
        raise SystemExit(10)
    if before.st_size <= 0 or before.st_size > maximum:
        raise SystemExit(11)

    digest = hashlib.sha256()
    byte_count = 0
    while True:
        block = os.read(descriptor, 1024 * 1024)
        if not block:
            break
        digest.update(block)
        byte_count += len(block)
    after = os.fstat(descriptor)
    identity = lambda value: (
        value.st_dev, value.st_ino, value.st_mode, value.st_uid, value.st_nlink,
        value.st_size, value.st_mtime_ns, value.st_ctime_ns,
    )
    if identity(after) != identity(before) or byte_count != before.st_size:
        raise SystemExit(12)
    if not hmac.compare_digest(digest.hexdigest(), expected):
        raise SystemExit(13)
finally:
    os.close(descriptor)
PY
}

run_retained_input_self_test() {
  local test_root test_file test_digest hard_link
  test_root="$(/usr/bin/mktemp -d "/private/tmp/nembra-retained-install-self-test.XXXXXX")"
  [[ "$test_root" == "/private/tmp/nembra-retained-install-self-test."* ]] || die "Self-test temporary path is invalid."
  /bin/chmod 700 "$test_root"
  test_file="$test_root/subject.json"
  builtin printf '%s\n' '{"selfTest":true}' > "$test_file"
  /bin/chmod 600 "$test_file"
  test_digest="$(/usr/bin/shasum -a 256 "$test_file" | /usr/bin/awk '{print $1}')"
  validate_retained_input "self-test subject" "$test_file" "$test_digest" private 1024

  /bin/ln -s "$test_file" "$test_root/substituted.json"
  if validate_retained_input "self-test substituted subject" "$test_root/substituted.json" "$test_digest" private 1024 2>/dev/null; then
    /bin/rm -rf -- "$test_root"
    die "Self-test accepted a symlinked retained subject."
  fi

  hard_link="$test_root/hard-linked.json"
  /bin/ln "$test_file" "$hard_link"
  if validate_retained_input "self-test hard-linked subject" "$hard_link" "$test_digest" private 1024 2>/dev/null; then
    /bin/rm -rf -- "$test_root"
    die "Self-test accepted a multiply linked retained subject."
  fi

  /bin/rm -rf -- "$test_root"
  say "Retained-input no-follow/hash/mode/link self-test passed"
}

case "${1:-}" in
  --self-test)
    [[ "$#" == 1 ]] || die "--self-test accepts no additional arguments."
    run_retained_input_self_test
    exit 0
    ;;
  --dry-run)
    [[ "$#" == 1 ]] || die "--dry-run accepts no additional arguments."
    ;;
  "") ;;
  *) die "Only --dry-run or --self-test is accepted; private values and hashes must not be placed on argv." ;;
esac

: "${NEMBRA_RETAINED_IPA_PATH:?Set NEMBRA_RETAINED_IPA_PATH to the absolute retained accepted signed IPA path.}"
: "${NEMBRA_RETAINED_IPA_SHA256:?Set NEMBRA_RETAINED_IPA_SHA256 to its independently accepted SHA-256.}"
: "${NEMBRA_RETAINED_INSTALL_MANIFEST_PATH:?Set NEMBRA_RETAINED_INSTALL_MANIFEST_PATH to the absolute canonical retained-install manifest path.}"
: "${NEMBRA_RETAINED_INSTALL_MANIFEST_SHA256:?Set NEMBRA_RETAINED_INSTALL_MANIFEST_SHA256 to its independently accepted SHA-256.}"
: "${NEMBRA_ACCEPTED_BUILD_SUBJECT_PATH:?Set NEMBRA_ACCEPTED_BUILD_SUBJECT_PATH to the absolute accepted external build-record path.}"
: "${NEMBRA_ACCEPTED_BUILD_SUBJECT_SHA256:?Set NEMBRA_ACCEPTED_BUILD_SUBJECT_SHA256.}"
: "${NEMBRA_ACCEPTED_EVIDENCE_SUBJECT_PATH:?Set NEMBRA_ACCEPTED_EVIDENCE_SUBJECT_PATH to the absolute signed build-evidence path.}"
: "${NEMBRA_ACCEPTED_EVIDENCE_SUBJECT_SHA256:?Set NEMBRA_ACCEPTED_EVIDENCE_SUBJECT_SHA256.}"
: "${NEMBRA_ACCEPTED_FINAL_GO_SUBJECT_PATH:?Set NEMBRA_ACCEPTED_FINAL_GO_SUBJECT_PATH to the absolute accepted Final-GO subject path.}"
: "${NEMBRA_ACCEPTED_FINAL_GO_SUBJECT_SHA256:?Set NEMBRA_ACCEPTED_FINAL_GO_SUBJECT_SHA256.}"
: "${NEMBRA_ACCEPTED_TUYA_LOCK_SUBJECT_PATH:?Set NEMBRA_ACCEPTED_TUYA_LOCK_SUBJECT_PATH to the absolute accepted Tuya-lock subject path.}"
: "${NEMBRA_ACCEPTED_TUYA_LOCK_SUBJECT_SHA256:?Set NEMBRA_ACCEPTED_TUYA_LOCK_SUBJECT_SHA256.}"
: "${NEMBRA_INTENDED_DEVICE_PSEUDONYMOUS_BINDING_PATH:?Set NEMBRA_INTENDED_DEVICE_PSEUDONYMOUS_BINDING_PATH to its absolute private path.}"
: "${NEMBRA_INTENDED_DEVICE_PSEUDONYMOUS_BINDING_SHA256:?Set NEMBRA_INTENDED_DEVICE_PSEUDONYMOUS_BINDING_SHA256.}"

validate_retained_input "retained accepted signed IPA" "$NEMBRA_RETAINED_IPA_PATH" "$NEMBRA_RETAINED_IPA_SHA256" public 1073741824
validate_retained_input "canonical retained-install manifest" "$NEMBRA_RETAINED_INSTALL_MANIFEST_PATH" "$NEMBRA_RETAINED_INSTALL_MANIFEST_SHA256" public 16384
validate_retained_input "accepted external build record" "$NEMBRA_ACCEPTED_BUILD_SUBJECT_PATH" "$NEMBRA_ACCEPTED_BUILD_SUBJECT_SHA256" public 1048576
validate_retained_input "accepted signed build evidence" "$NEMBRA_ACCEPTED_EVIDENCE_SUBJECT_PATH" "$NEMBRA_ACCEPTED_EVIDENCE_SUBJECT_SHA256" public 1048576
validate_retained_input "accepted Final-GO subject" "$NEMBRA_ACCEPTED_FINAL_GO_SUBJECT_PATH" "$NEMBRA_ACCEPTED_FINAL_GO_SUBJECT_SHA256" private 1048576
validate_retained_input "accepted Tuya-lock subject" "$NEMBRA_ACCEPTED_TUYA_LOCK_SUBJECT_PATH" "$NEMBRA_ACCEPTED_TUYA_LOCK_SUBJECT_SHA256" public 4194304
validate_retained_input "intended-device pseudonymous binding" "$NEMBRA_INTENDED_DEVICE_PSEUDONYMOUS_BINDING_PATH" "$NEMBRA_INTENDED_DEVICE_PSEUDONYMOUS_BINDING_SHA256" private 1048576

# The semantic cross-binding code is part of the accepted Capture source, not caller data. Capture
# exact nested-tool bytes from the immutable Git objects for the current clean checkout before any
# import. A same-UID working-tree edit after this point therefore cannot replace the verifier logic.
SOURCE_SHA="$(GIT_NO_REPLACE_OBJECTS=1 /usr/bin/git -C "$ROOT" rev-parse --verify 'HEAD^{commit}' | /usr/bin/tr '[:upper:]' '[:lower:]')"
[[ "$SOURCE_SHA" =~ ^[0-9a-f]{40}$ ]] || die "Current Capture source commit identity is malformed."
[[ -z "$(GIT_NO_REPLACE_OBJECTS=1 /usr/bin/git -C "$ROOT" status --porcelain=v1 --untracked-files=all)" ]] || die "Capture checkout has local changes; nested authority code must come from one clean accepted source."

NESTED_TOOL_ROOT="$(/usr/bin/mktemp -d "/private/tmp/nembra-retained-install-tools.XXXXXX")"
[[ "$NESTED_TOOL_ROOT" == "/private/tmp/nembra-retained-install-tools."* ]] || die "Nested-tool temporary path is invalid."
/bin/chmod 700 "$NESTED_TOOL_ROOT"
cleanup_nested_tools() {
  if [[ -n "${NESTED_TOOL_ROOT:-}" && -d "$NESTED_TOOL_ROOT" ]]; then
    /bin/rm -rf -- "$NESTED_TOOL_ROOT"
  fi
}
trap cleanup_nested_tools EXIT

capture_accepted_git_tool() {
  local repository_path="$1"
  local destination="$2"
  local blob actual_blob

  blob="$(GIT_NO_REPLACE_OBJECTS=1 /usr/bin/git -C "$ROOT" rev-parse "$SOURCE_SHA:$repository_path" 2>/dev/null)" || die "Accepted nested retained-install tool is missing: $repository_path"
  [[ "$blob" =~ ^[0-9a-f]{40}$ ]] || die "Accepted nested retained-install tool Git identity is malformed: $repository_path"
  GIT_NO_REPLACE_OBJECTS=1 /usr/bin/git -C "$ROOT" cat-file blob "$blob" > "$destination" || die "Could not capture accepted nested retained-install tool: $repository_path"
  /bin/chmod 600 "$destination"
  actual_blob="$(GIT_NO_REPLACE_OBJECTS=1 /usr/bin/git -C "$ROOT" hash-object "$destination")" || die "Could not authenticate captured nested retained-install tool: $repository_path"
  [[ "$actual_blob" == "$blob" ]] || die "Captured nested retained-install tool does not match its accepted Git object: $repository_path"
}

capture_accepted_git_tool \
  "scripts/ci/es80_retained_install_cross_binding.py" \
  "$NESTED_TOOL_ROOT/es80_retained_install_cross_binding.py"
capture_accepted_git_tool \
  "scripts/ci/es80_retained_install_manifest.py" \
  "$NESTED_TOOL_ROOT/es80_retained_install_manifest.py"

# Re-read only the small JSON subjects through no-follow descriptors and prove they all name one
# identical retained install. The independently accepted IPA/Tuya/device digests are inputs; the IPA
# itself is never loaded into this Python process. The semantic helper and its manifest dependency
# are imported only from the Git-authenticated private snapshots captured above.
/usr/bin/env -i \
  PATH=/usr/bin:/bin \
  LC_ALL=C \
  /usr/bin/python3 -I -B - \
    "$NESTED_TOOL_ROOT" "$SOURCE_SHA" \
    "$NEMBRA_RETAINED_INSTALL_MANIFEST_PATH" "$NEMBRA_RETAINED_INSTALL_MANIFEST_SHA256" \
    "$NEMBRA_ACCEPTED_BUILD_SUBJECT_PATH" "$NEMBRA_ACCEPTED_BUILD_SUBJECT_SHA256" \
    "$NEMBRA_ACCEPTED_EVIDENCE_SUBJECT_PATH" "$NEMBRA_ACCEPTED_EVIDENCE_SUBJECT_SHA256" \
    "$NEMBRA_ACCEPTED_FINAL_GO_SUBJECT_PATH" "$NEMBRA_ACCEPTED_FINAL_GO_SUBJECT_SHA256" \
    "$NEMBRA_RETAINED_IPA_SHA256" "$NEMBRA_ACCEPTED_TUYA_LOCK_SUBJECT_SHA256" \
    "$NEMBRA_INTENDED_DEVICE_PSEUDONYMOUS_BINDING_SHA256" <<'PY'
import hashlib
import hmac
import importlib.util
import os
import stat
import sys
from pathlib import Path, PurePath

(
    tool_root_raw, source_sha,
    manifest_path, manifest_sha,
    build_path, build_sha,
    evidence_path, evidence_sha,
    final_go_path, final_go_sha,
    retained_ipa_sha, tuya_lock_sha, device_binding_sha,
) = sys.argv[1:]


def read_exact(path_raw: str, expected: str, maximum: int) -> bytes:
    path = PurePath(path_raw)
    no_follow = getattr(os, "O_NOFOLLOW", None)
    if no_follow is None or not path_raw.startswith("/"):
        raise RuntimeError("secure retained-subject read is unavailable")
    directory_fd = os.open("/", os.O_RDONLY | os.O_DIRECTORY)
    try:
        for component in path.parts[1:-1]:
            next_fd = os.open(component, os.O_RDONLY | os.O_DIRECTORY | no_follow, dir_fd=directory_fd)
            os.close(directory_fd)
            directory_fd = next_fd
        descriptor = os.open(path.parts[-1], os.O_RDONLY | no_follow, dir_fd=directory_fd)
    finally:
        os.close(directory_fd)
    try:
        before = os.fstat(descriptor)
        if not stat.S_ISREG(before.st_mode) or before.st_nlink != 1 or before.st_size <= 0 or before.st_size > maximum:
            raise RuntimeError("retained subject identity changed")
        data = bytearray()
        while len(data) <= maximum:
            block = os.read(descriptor, min(65536, maximum + 1 - len(data)))
            if not block:
                break
            data.extend(block)
        after = os.fstat(descriptor)
        identity = lambda value: (
            value.st_dev, value.st_ino, value.st_mode, value.st_uid, value.st_nlink,
            value.st_size, value.st_mtime_ns, value.st_ctime_ns,
        )
        if identity(before) != identity(after) or len(data) != before.st_size:
            raise RuntimeError("retained subject changed during read")
        actual = hashlib.sha256(data).hexdigest()
        if not hmac.compare_digest(actual, expected.lower()):
            raise RuntimeError("retained subject digest changed")
        return bytes(data)
    finally:
        os.close(descriptor)

tool_root = Path(tool_root_raw)
helper_path = tool_root / "es80_retained_install_cross_binding.py"
spec = importlib.util.spec_from_file_location("nembra_retained_install_cross_binding", helper_path)
if spec is None or spec.loader is None:
    raise RuntimeError("retained-install cross-binding helper is unavailable")
helper = importlib.util.module_from_spec(spec)
spec.loader.exec_module(helper)
verified_manifest = helper.verify_cross_binding(
    install_manifest_data=read_exact(manifest_path, manifest_sha, 16_384),
    external_build_record_data=read_exact(build_path, build_sha, 1_048_576),
    signed_build_evidence_data=read_exact(evidence_path, evidence_sha, 1_048_576),
    final_go_record_data=read_exact(final_go_path, final_go_sha, 1_048_576),
    accepted_install_manifest_sha256=manifest_sha.lower(),
    accepted_retained_ipa_sha256=retained_ipa_sha.lower(),
    accepted_external_build_record_sha256=build_sha.lower(),
    accepted_signed_build_evidence_sha256=evidence_sha.lower(),
    accepted_final_go_record_sha256=final_go_sha.lower(),
    accepted_tuya_lock_sha256=tuya_lock_sha.lower(),
    accepted_intended_device_pseudonym_sha256=device_binding_sha.lower(),
)
if verified_manifest.get("sourceCommitSHA") != source_sha:
    raise RuntimeError("retained manifest source commit does not match the accepted installer checkout")
PY

say "Stable retained-install subjects cross-bound to one canonical manifest"
say "PREINSTALL_RETAINED_SUBJECTS_BOUND_NOT_INSTALL_AUTHORITY"
die "Installation remains blocked: the production trust root and standalone app capability lifecycle are not independently accepted. The per-attempt authorization envelope must be created only after the installed app emits its fresh challenge. No device was contacted and no app was installed. Status: $RETAINED_INSTALL_CONTRACT_STATUS"
