#!/usr/bin/env python3
"""Exploit-positive witness for tracked-ancestor aliases in generated input staging.

A terminally passing test means the validation parent permits a tracked symlink that
is an ancestor of a generated/private subject to redirect copied bytes into the
tracked-source namespace. This is validation evidence only, never product authority.
"""
from __future__ import annotations

import importlib.util
from pathlib import Path
import subprocess
import tempfile
import unittest

HELPER = Path(__file__).resolve().parents[1] / "capture_accepted_build_input_snapshot.py"
spec = importlib.util.spec_from_file_location("snapshot_ancestor_alias", HELPER)
assert spec and spec.loader
snapshot = importlib.util.module_from_spec(spec)
spec.loader.exec_module(snapshot)


def git(repo: Path, *args: str) -> str:
    completed = subprocess.run(
        ["git", "-C", str(repo), *args],
        text=True,
        capture_output=True,
        check=True,
    )
    return completed.stdout.strip()


def seed_accepted_source(root: Path) -> str:
    git(root, "init", "-q")
    git(root, "config", "user.email", "capture-red-team@example.invalid")
    git(root, "config", "user.name", "Capture Red Team")

    sources = root / "Sources"
    sources.mkdir()
    (sources / "App.swift").write_text("let accepted = true\n", encoding="utf-8")

    # This tracked alias is accepted Git input. It is deliberately an ancestor of
    # LocalSecrets/TuyaSDK and LocalSecrets/TuyaRuntime, but the current collision
    # predicate checks only the opposite direction (tracked paths below a generated
    # subject). The target remains inside the accepted source root, so the tracked
    # symlink materializer accepts it.
    (root / "LocalSecrets").symlink_to("Sources", target_is_directory=True)

    git(root, "add", "Sources/App.swift", "LocalSecrets")
    git(root, "commit", "-qm", "accepted source with ancestor alias")
    return git(root, "rev-parse", "HEAD")


def seed_generated_inputs(root: Path) -> None:
    (root / "Podfile.lock").write_text("PODS:\n  - Fixture (1.0)\n", encoding="utf-8")

    workspace = root / "NembraCapture.xcworkspace"
    workspace.mkdir()
    (workspace / "contents.xcworkspacedata").write_text("<Workspace/>\n", encoding="utf-8")

    pods = root / "Pods/Fixture"
    pods.mkdir(parents=True)
    (pods / "libFixture.a").write_bytes(b"generated-public-pod")

    # These writes traverse the tracked LocalSecrets -> Sources alias in the mutable
    # field tree. They are intentionally untracked and become the generated/private
    # candidate manifest that stage_accepted_build_inputs later accepts.
    sdk = root / "LocalSecrets/TuyaSDK"
    (sdk / "Build").mkdir(parents=True)
    (sdk / "ThingSmartCryption.podspec").write_text("Pod::Spec.new\n", encoding="utf-8")
    (sdk / "Build/libThingSmartCryption.a").write_bytes(b"private-sdk-fixture")

    runtime = root / "LocalSecrets/TuyaRuntime/Sources/NembraTuyaPrivateConfig"
    runtime.mkdir(parents=True)
    (root / "LocalSecrets/TuyaRuntime/NembraTuyaPrivateConfig.podspec").write_text(
        "Pod::Spec.new\n", encoding="utf-8"
    )
    (runtime / "Identity.swift").write_text(
        'let privateIdentity = "fixture"\n', encoding="utf-8"
    )


class GeneratedInputAncestorAliasRedTeamTests(unittest.TestCase):
    def test_tracked_ancestor_symlink_redirects_generated_bytes_into_tracked_namespace(self) -> None:
        with tempfile.TemporaryDirectory(prefix="nembra-generated-alias-red-team-") as raw:
            repo = Path(raw) / "repo"
            repo.mkdir()
            source_sha = seed_accepted_source(repo)
            seed_generated_inputs(repo)

            tracked = {
                relative
                for _mode, _kind, _oid, relative in snapshot._git_tree_entries(repo, source_sha)
            }
            self.assertIn(Path("LocalSecrets"), tracked)
            self.assertNotIn(Path("Sources/TuyaSDK/ThingSmartCryption.podspec"), tracked)

            accepted_manifest = snapshot.generated_manifest_sha256(repo, source_sha)
            destination = Path(raw) / "stage"

            # Exploit-positive condition on the current parent: admission succeeds.
            actual = snapshot.stage_accepted_build_inputs(
                repo,
                source_sha,
                destination,
                accepted_manifest,
            )
            self.assertEqual(actual, accepted_manifest)

            # The accepted tracked symlink survives exact Git materialization, so the
            # generated/private copy has populated Sources/* rather than a disjoint
            # LocalSecrets subtree. The compiler can now observe generated bytes inside
            # a namespace that the accepted source SHA did not contain.
            self.assertTrue((destination / "LocalSecrets").is_symlink())
            redirected = destination / "Sources/TuyaSDK/ThingSmartCryption.podspec"
            self.assertTrue(redirected.is_file())
            self.assertEqual(redirected.read_text(encoding="utf-8"), "Pod::Spec.new\n")
            self.assertTrue(
                (destination / "Sources/TuyaRuntime/Sources/NembraTuyaPrivateConfig/Identity.swift").is_file()
            )


if __name__ == "__main__":
    unittest.main(verbosity=2)
