#!/usr/bin/env python3
"""Focused custody tests for accepted CocoaPods-generated bytes across xcodebuild."""

from __future__ import annotations

import importlib.util
from pathlib import Path
import sys
import tempfile
import unittest

REPOSITORY = Path(__file__).resolve().parents[3]
GUARD_PATH = REPOSITORY / "Scripts/capture_tuya_private_input_build_guard.py"

spec = importlib.util.spec_from_file_location("capture_build_guard", GUARD_PATH)
assert spec is not None and spec.loader is not None
guard = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = guard
spec.loader.exec_module(guard)


class QuietBackend:
    def register(self, descriptor: int) -> None:
        del descriptor

    def events(self, timeout: float):
        del timeout
        return ()

    def close(self) -> None:
        pass


class FinishedProcess:
    returncode = 0

    def poll(self):
        return 0

    def terminate(self) -> None:
        pass

    def wait(self, timeout=None):
        del timeout
        return 0

    def kill(self) -> None:
        pass


class CocoaPodsBuildWindowGuardTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory(prefix="nembra-generated-build-guard-")
        self.root = Path(self.temporary.name)
        self.lock = self.root / "Podfile.lock"
        self.lock.write_text("PODS:\n  - ThingSmartHomeKit (7.8.0)\n", encoding="utf-8")
        self.security_podspec = self.root / "ThingSmartCryption.podspec"
        self.security_podspec.write_text("Pod::Spec.new do |s|\nend\n", encoding="utf-8")
        self.security_build = self.root / "SecurityBuild"
        self.security_build.mkdir()
        (self.security_build / "lib.a").write_bytes(b"security")
        self.identity_podspec = self.root / "Identity.podspec"
        self.identity_podspec.write_text("Pod::Spec.new do |s|\nend\n", encoding="utf-8")
        self.identity_sources = self.root / "IdentitySources"
        self.identity_sources.mkdir()
        (self.identity_sources / "Identity.swift").write_text("let configured = true\n", encoding="utf-8")
        self.pods = self.root / "Pods"
        self.pods.mkdir()
        self.generated = self.pods / "Pods-NembraCapture.debug.xcconfig"
        self.generated.write_text("FLAG=REVIEWED\n", encoding="utf-8")
        self.workspace = self.root / "NembraCapture.xcworkspace"
        self.workspace.mkdir()
        (self.workspace / "contents.xcworkspacedata").write_text("REVIEWED\n", encoding="utf-8")
        self.accepted = guard.cocoapods_subject.digest_generated_subject(self.pods, self.workspace)

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def inputs(self, accepted: str | None = None):
        return guard.PrivateInputs(
            lockfile=self.lock,
            security_podspec=self.security_podspec,
            security_build=self.security_build,
            identity_podspec=self.identity_podspec,
            identity_sources=self.identity_sources,
            generated_pods=self.pods,
            generated_workspace=self.workspace,
            accepted_generated_sha256=self.accepted if accepted is None else accepted,
        )

    def test_changed_generated_subject_is_rejected_before_child_start(self) -> None:
        self.generated.write_text("FLAG=SUBSTITUTED\n", encoding="utf-8")
        spawned = False

        def popen(_command):
            nonlocal spawned
            spawned = True
            return FinishedProcess()

        with self.assertRaisesRegex(guard.BuildGuardError, "changed after bootstrap acceptance"):
            guard.run_guarded_build(
                self.inputs(),
                ["fake-xcodebuild"],
                backend_factory=QuietBackend,
                popen_factory=popen,
            )
        self.assertFalse(spawned, "changed generated subject must fail before xcodebuild starts")

    def test_transient_build_window_mutation_is_rejected_even_without_backend_event(self) -> None:
        def popen(_command):
            self.generated.write_text("FLAG=MUTATED-DURING-BUILD\n", encoding="utf-8")
            return FinishedProcess()

        with self.assertRaisesRegex(guard.BuildGuardError, "changed across the guarded xcodebuild window"):
            guard.run_guarded_build(
                self.inputs(),
                ["fake-xcodebuild"],
                backend_factory=QuietBackend,
                popen_factory=popen,
            )

    def test_unchanged_exact_subject_is_admitted(self) -> None:
        result = guard.run_guarded_build(
            self.inputs(),
            ["fake-xcodebuild"],
            backend_factory=QuietBackend,
            popen_factory=lambda _command: FinishedProcess(),
        )
        self.assertEqual(result, 0)


if __name__ == "__main__":
    unittest.main(verbosity=2)
