#!/usr/bin/env python3
from __future__ import annotations

import importlib.util
from pathlib import Path
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[3]
HELPER = ROOT / "Scripts/capture_cocoapods_generated_build_subject.py"
BOOTSTRAP = ROOT / "Scripts/bootstrap_capture_tuya_sdk.sh"
BUILD_GUARD = ROOT / "Scripts/capture_tuya_private_input_build_guard.py"


def load_helper():
    spec = importlib.util.spec_from_file_location("cocoapods_subject", HELPER)
    if spec is None or spec.loader is None:
        raise RuntimeError("could not load generated build-subject helper")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def make_subject(root: Path) -> tuple[Path, Path, Path, Path]:
    pods = root / "Pods"
    support = pods / "Target Support Files/Pods-NembraCapture"
    workspace = root / "NembraCapture.xcworkspace"
    support.mkdir(parents=True)
    workspace.mkdir()
    config = support / "Pods-NembraCapture.debug.xcconfig"
    data = workspace / "contents.xcworkspacedata"
    config.write_text("GRAPH=A\n", encoding="utf-8")
    data.write_text("A\n", encoding="utf-8")
    return pods, workspace, config, data


class CocoaPodsGeneratedBuildSubjectTests(unittest.TestCase):
    def test_generated_build_bytes_change_subject_digest(self) -> None:
        module = load_helper()
        with tempfile.TemporaryDirectory(prefix="nembra-cocoapods-subject-") as temporary:
            root = Path(temporary)
            pods, workspace, config, data = make_subject(root)
            reviewed = module.fingerprint_subject(pods, workspace)
            config.write_text("GRAPH=B\n", encoding="utf-8")
            data.write_text("B\n", encoding="utf-8")
            substituted = module.fingerprint_subject(pods, workspace)
            self.assertRegex(reviewed, r"^[0-9a-f]{64}$")
            self.assertRegex(substituted, r"^[0-9a-f]{64}$")
            self.assertNotEqual(reviewed, substituted)

    def test_external_symlink_requires_explicit_separately_guarded_root(self) -> None:
        module = load_helper()
        with tempfile.TemporaryDirectory(prefix="nembra-cocoapods-symlink-") as temporary:
            root = Path(temporary)
            pods, workspace, _, _ = make_subject(root)
            private_root = root / "LocalSecrets/TuyaSDK"
            private_root.mkdir(parents=True)
            (private_root / "private.a").write_bytes(b"private")
            (pods / "DevelopmentPod").symlink_to(private_root, target_is_directory=True)

            with self.assertRaises(module.SubjectError):
                module.fingerprint_subject(pods, workspace)

            admitted = module.fingerprint_subject(
                pods,
                workspace,
                separately_guarded_external_roots=(private_root,),
            )
            self.assertRegex(admitted, r"^[0-9a-f]{64}$")

    def test_bootstrap_binds_reviewed_generated_subject_before_field_build(self) -> None:
        source = BOOTSTRAP.read_text(encoding="utf-8")
        fingerprint = source.index("COCOAPODS_BUILD_SUBJECT_SHA256=\"")
        missing_authority = source.index("generated CocoaPods build subject has no preaccepted SHA-256 authority")
        mismatch = source.index("same Podfile.lock produced different build-affecting generated bytes")
        self.assertLess(fingerprint, missing_authority)
        self.assertLess(missing_authority, mismatch)
        self.assertIn("NEMBRA_CAPTURE_ACCEPTED_COCOAPODS_BUILD_SUBJECT_SHA256", source)
        self.assertIn("--resolve-lock-for-review", source)
        self.assertIn("CocoaPods build subject SHA-256", source)
        self.assertEqual(source.count("--separately-guarded-external-root"), 2)
        self.assertIn('"$TUYA_PRIVATE_SDK"', source)
        self.assertIn('"$TUYA_PRIVATE_IDENTITY"', source)

    def test_existing_xcodebuild_guard_owns_exact_preaccepted_generated_subject(self) -> None:
        source = BUILD_GUARD.read_text(encoding="utf-8")
        loader = source.index("capture_cocoapods_generated_build_subject.py")
        generated_snapshot = source.index("generated_build_subject.fingerprint_subject")
        expected_environment = source.index(
            'os.environ.get("NEMBRA_CAPTURE_ACCEPTED_COCOAPODS_BUILD_SUBJECT_SHA256")'
        )
        prebuild_match = source.index(
            "generated CocoaPods build subject no longer matches the preaccepted SHA-256 before xcodebuild"
        )
        watcher = source.index("inputs.generated_pods")
        xcodebuild = source.index("process = popen_factory(list(command))")
        final_snapshot = source.rindex("final_snapshot = inputs.generation_snapshot()")
        self.assertLess(loader, generated_snapshot)
        self.assertLess(generated_snapshot, watcher)
        self.assertLess(prebuild_match, xcodebuild)
        self.assertLess(xcodebuild, final_snapshot)
        self.assertLess(final_snapshot, expected_environment)
        self.assertIn("inputs.generated_workspace", source)
        self.assertIn("separately_guarded_external_roots", source)
        self.assertIn("self.security_podspec.parent", source)
        self.assertIn("self.identity_podspec.parent", source)
        self.assertIn("field build inputs changed across the guarded xcodebuild window", source)
        self.assertIn("generated CocoaPods build subject lost preaccepted authority across xcodebuild", source)

    def test_helper_has_no_second_build_window_authority(self) -> None:
        source = HELPER.read_text(encoding="utf-8")
        self.assertNotIn("subprocess.Popen", source)
        self.assertNotIn("select.kqueue", source)
        self.assertIn("separately_guarded_external_roots", source)
        self.assertIn("generated build symlink escapes", source)


if __name__ == "__main__":
    unittest.main(verbosity=2)
