#!/usr/bin/env python3
from __future__ import annotations

import importlib.util
from pathlib import Path
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[3]
HELPER = ROOT / "Scripts/capture_cocoapods_generated_build_subject.py"
BOOTSTRAP = ROOT / "Scripts/bootstrap_capture_tuya_sdk.sh"
BUILD_GUARD = ROOT / "Scripts/capture_tuya_private_input_build_guard.py"


def load_helper():
    spec = importlib.util.spec_from_file_location("cocoapods_subject", HELPER)
    if spec is None or spec.loader is None:
        raise RuntimeError("could not load generated build-subject helper")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class CocoaPodsGeneratedBuildSubjectTests(unittest.TestCase):
    def test_generated_build_bytes_change_subject_digest(self) -> None:
        module = load_helper()
        with tempfile.TemporaryDirectory(prefix="nembra-cocoapods-subject-") as temporary:
            root = Path(temporary)
            pods = root / "Pods/Target Support Files/Pods-NembraCapture"
            workspace = root / "NembraCapture.xcworkspace"
            pods.mkdir(parents=True)
            workspace.mkdir()
            config = pods / "Pods-NembraCapture.debug.xcconfig"
            data = workspace / "contents.xcworkspacedata"
            config.write_text("GRAPH=A\n", encoding="utf-8")
            data.write_text("A\n", encoding="utf-8")
            reviewed = module.fingerprint_subject(root / "Pods", workspace)
            config.write_text("GRAPH=B\n", encoding="utf-8")
            data.write_text("B\n", encoding="utf-8")
            substituted = module.fingerprint_subject(root / "Pods", workspace)
            self.assertRegex(reviewed, r"^[0-9a-f]{64}$")
            self.assertRegex(substituted, r"^[0-9a-f]{64}$")
            self.assertNotEqual(reviewed, substituted)

    def test_bootstrap_binds_reviewed_generated_subject_before_field_build(self) -> None:
        source = BOOTSTRAP.read_text(encoding="utf-8")
        fingerprint = source.index("COCOAPODS_BUILD_SUBJECT_SHA256=\"")
        missing_authority = source.index("generated CocoaPods build subject has no preaccepted SHA-256 authority")
        mismatch = source.index("same Podfile.lock produced different build-affecting generated bytes")
        self.assertLess(fingerprint, missing_authority)
        self.assertLess(missing_authority, mismatch)
        self.assertIn("NEMBRA_CAPTURE_ACCEPTED_COCOAPODS_BUILD_SUBJECT_SHA256", source)
        self.assertIn("--resolve-lock-for-review", source)
        self.assertIn("CocoaPods build subject SHA-256", source)

    def test_existing_xcodebuild_guard_owns_generated_subject(self) -> None:
        source = BUILD_GUARD.read_text(encoding="utf-8")
        loader = source.index("capture_cocoapods_generated_build_subject.py")
        generated_snapshot = source.index("generated_build_subject.fingerprint_subject")
        watcher = source.index("inputs.generated_pods")
        xcodebuild = source.index("process = popen_factory(list(command))")
        final_snapshot = source.rindex("final_snapshot = inputs.generation_snapshot()")
        self.assertLess(loader, generated_snapshot)
        self.assertLess(generated_snapshot, watcher)
        self.assertLess(watcher, xcodebuild)
        self.assertLess(xcodebuild, final_snapshot)
        self.assertIn("inputs.generated_workspace", source)
        self.assertIn("field build inputs changed across the guarded xcodebuild window", source)

    def test_generated_helper_keeps_independent_mac_guard_available(self) -> None:
        source = HELPER.read_text(encoding="utf-8")
        self.assertIn("kqueue", source)
        self.assertIn("KQ_NOTE_WRITE", source)
        self.assertIn("generated CocoaPods build subject changed while xcodebuild was running", source)
        self.assertIn("subparsers.add_parser(\"guard\")", source)


if __name__ == "__main__":
    unittest.main(verbosity=2)
