#!/usr/bin/env python3
"""Expected-red: the build guard must rebind generated bytes to external review authority."""

from __future__ import annotations

import importlib.util
import os
from pathlib import Path
import sys
import tempfile
import unittest

REPOSITORY = Path(__file__).resolve().parents[3]
GUARD_PATH = REPOSITORY / "Scripts/capture_tuya_private_input_build_guard.py"
SUBJECT_PATH = REPOSITORY / "Scripts/capture_cocoapods_build_subject.py"


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"could not load {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


guard = load_module("capture_build_guard_rebind_test", GUARD_PATH)
subject = load_module("capture_generated_subject_rebind_test", SUBJECT_PATH)


class QuietBackend:
    def register(self, descriptor: int) -> None:
        del descriptor

    def events(self, timeout: float):
        del timeout
        return ()

    def close(self) -> None:
        pass


class FinishedProcess:
    returncode = 0

    def poll(self):
        return 0

    def terminate(self) -> None:
        pass

    def wait(self, timeout=None):
        del timeout
        return 0

    def kill(self) -> None:
        pass


class BootstrapGuardRebindTests(unittest.TestCase):
    def test_substitution_after_bootstrap_is_rejected_before_xcodebuild(self) -> None:
        with tempfile.TemporaryDirectory(prefix="nembra-bootstrap-guard-rebind-") as temporary:
            root = Path(temporary)
            lock = root / "Podfile.lock"
            lock.write_text("PODS:\n  - ThingSmartHomeKit (7.8.0)\n", encoding="utf-8")

            security_podspec = root / "ThingSmartCryption.podspec"
            security_podspec.write_text("Pod::Spec.new do |s|\nend\n", encoding="utf-8")
            security_build = root / "SecurityBuild"
            security_build.mkdir()
            (security_build / "libThingSmartCryption.a").write_bytes(b"security")

            identity_podspec = root / "Identity.podspec"
            identity_podspec.write_text("Pod::Spec.new do |s|\nend\n", encoding="utf-8")
            identity_sources = root / "IdentitySources"
            identity_sources.mkdir()
            (identity_sources / "Identity.swift").write_text("let configured = true\n", encoding="utf-8")

            pods = root / "Pods"
            generated_dir = pods / "Target Support Files/Pods-NembraCapture"
            generated_dir.mkdir(parents=True)
            generated = generated_dir / "Pods-NembraCapture.debug.xcconfig"
            generated.write_text("FLAG = REVIEWED\n", encoding="utf-8")
            workspace = root / "NembraCapture.xcworkspace"
            workspace.mkdir()
            (workspace / "contents.xcworkspacedata").write_text("REVIEWED\n", encoding="utf-8")

            accepted = subject.subject_digest(lockfile=lock, pods=pods, workspace=workspace)
            generated.write_text("FLAG = SUBSTITUTED\n", encoding="utf-8")
            self.assertNotEqual(
                subject.subject_digest(lockfile=lock, pods=pods, workspace=workspace),
                accepted,
                "fixture must actually replace the reviewed generated subject",
            )

            inputs = guard.PrivateInputs(
                lockfile=lock,
                security_podspec=security_podspec,
                security_build=security_build,
                identity_podspec=identity_podspec,
                identity_sources=identity_sources,
            )
            spawned = False

            def popen(_command):
                nonlocal spawned
                spawned = True
                return FinishedProcess()

            previous = os.environ.get("NEMBRA_CAPTURE_ACCEPTED_COCOAPODS_BUILD_SUBJECT_SHA256")
            os.environ["NEMBRA_CAPTURE_ACCEPTED_COCOAPODS_BUILD_SUBJECT_SHA256"] = accepted
            try:
                try:
                    guard.run_guarded_build(
                        inputs,
                        ["fake-xcodebuild"],
                        backend_factory=QuietBackend,
                        popen_factory=popen,
                    )
                except (guard.BuildGuardError, subject.GeneratedSubjectError):
                    pass
            finally:
                if previous is None:
                    os.environ.pop("NEMBRA_CAPTURE_ACCEPTED_COCOAPODS_BUILD_SUBJECT_SHA256", None)
                else:
                    os.environ["NEMBRA_CAPTURE_ACCEPTED_COCOAPODS_BUILD_SUBJECT_SHA256"] = previous

            self.assertFalse(
                spawned,
                "xcodebuild started on generated bytes that did not match the externally accepted post-bootstrap subject",
            )


if __name__ == "__main__":
    unittest.main(verbosity=2)
