#!/usr/bin/env python3
"""Adversarial diagnostics for CocoaPods generated-build authority.

This test intentionally targets the active generated-build-subject repair lineage.
A reviewed digest is not sufficient unless it describes one coherent generation and
the accepted generated bytes remain under custody for the entire xcodebuild window.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path
import tempfile
import unittest
from unittest import mock

REPOSITORY = Path(__file__).resolve().parents[3]
SUBJECT_HELPER = REPOSITORY / "Scripts" / "capture_cocoapods_build_subject.py"
BUILD_GUARD = REPOSITORY / "Scripts" / "capture_tuya_private_input_build_guard.py"
INSTALLER = REPOSITORY / "scripts" / "field" / "install_one_time_capture.command"


def load_subject_helper():
    spec = importlib.util.spec_from_file_location("nembra_cocoapods_subject", SUBJECT_HELPER)
    if spec is None or spec.loader is None:
        raise RuntimeError("generated build-subject helper could not be loaded")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class CocoaPodsBuildWindowCustodyTests(unittest.TestCase):
    def test_subject_rejects_cross_tree_generation_change(self) -> None:
        """Pods must still be the same generation after workspace hashing finishes."""
        helper = load_subject_helper()
        with tempfile.TemporaryDirectory(prefix="nembra-cocoapods-cross-tree-") as temporary:
            root = Path(temporary)
            pods = root / "Pods"
            workspace = root / "NembraCapture.xcworkspace"
            pods.mkdir()
            workspace.mkdir()
            generated = pods / "Target Support Files" / "Pods-NembraCapture"
            generated.mkdir(parents=True)
            xcconfig = generated / "Pods-NembraCapture.debug.xcconfig"
            xcconfig.write_text("A\n", encoding="utf-8")
            (workspace / "contents.xcworkspacedata").write_text("workspace\n", encoding="utf-8")

            original_tree_digest = helper._tree_digest

            def mutate_after_pods(root_path: Path, label: bytes):
                result = original_tree_digest(root_path, label)
                if label == b"Pods":
                    # Same-size in-place replacement after the Pods tree has already
                    # passed its local revalidation. A coherent two-tree witness must
                    # notice this before returning authority for the pair.
                    xcconfig.write_text("B\n", encoding="utf-8")
                return result

            with mock.patch.object(helper, "_tree_digest", side_effect=mutate_after_pods):
                with self.assertRaises(
                    helper.BuildSubjectError,
                    msg=(
                        "generated build-subject helper returned a digest after Pods changed "
                        "between the Pods and workspace witnesses; revalidate both trees as one generation"
                    ),
                ):
                    helper.build_subject_digest(pods, workspace)

    def test_xcodebuild_window_custodies_generated_subject(self) -> None:
        """Pre-build equality cannot replace custody while the compiler consumes ignored bytes."""
        guard_source = BUILD_GUARD.read_text(encoding="utf-8")
        installer_source = INSTALLER.read_text(encoding="utf-8")

        existing_guard_covers_generated = all(
            marker in guard_source
            for marker in (
                "capture_cocoapods_build_subject",
                "NembraCapture.xcworkspace",
                "Pods",
            )
        )
        dedicated_generated_guard = (
            "cocoapods" in installer_source.lower()
            and "build_subject" in installer_source.lower()
            and "guard" in installer_source.lower()
            and "xcodebuild" in installer_source
        )

        self.assertTrue(
            existing_guard_covers_generated or dedicated_generated_guard,
            "the accepted CocoaPods generated subject is checked at bootstrap but is not under explicit custody across xcodebuild; "
            "a same-UID mutation/restore can otherwise feed unreviewed ignored bytes to the compiler",
        )


if __name__ == "__main__":
    unittest.main(verbosity=2)
