#!/usr/bin/env python3
"""Canonical hardened entrypoint for the external V14 ES80 TODAY Final GO record.

The Final GO foundation remains the closed-world validator for signed candidate, independent
crosscheck, install/runtime rendezvous, and operator attestation. This executable loads that
foundation directly; the historical `es80_today_final_go_record.py` compatibility module is
non-authorizing for both direct execution and imported builder calls.

This entrypoint removes the authority defects that must not remain on the executable GO path:
- trusted Xcode acceptance comes only from the owner-commanded default-branch workflow whose Git
  blob is pinned independently from the candidate PR head;
- trusted workflow Git-object lookup reuses the foundation's producer-owned, closed Git custody
  boundary rather than caller PATH/config/replacement semantics;
- the independent retained-candidate crosscheck is regenerated by executing its pinned reviewed Git
  blob under isolated producer-owned custody instead of trusting caller-written PASS JSON; and
- record publication is failure-atomic after no-replace publication.

No physical result is created by this tool. A generated GO record is procedural authorization for
one stationary passive Experiment One only after all supplied evidence is already legitimate.
"""
from __future__ import annotations

import importlib.util
import json
from pathlib import Path
import sys
import tempfile
from typing import Any, Callable

MODULE_DIR = Path(__file__).resolve().parent


def _load(name: str, filename: str):
    spec = importlib.util.spec_from_file_location(name, MODULE_DIR / filename)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"could not load {filename}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


foundation = _load("nembra_final_go_foundation", "es80_today_final_go_foundation.py")
trusted_xcode = _load(
    "nembra_trusted_capture_xcode_subject",
    "es80_today_trusted_capture_xcode_subject.py",
)
trusted_crosscheck = _load(
    "nembra_trusted_crosscheck_execution",
    "es80_today_trusted_crosscheck_execution.py",
)
publication = _load("nembra_final_go_publication", "es80_today_final_go_publication.py")

FinalGoError = foundation.FinalGoError


def _workflow_blob_sha_at_commit(tooling_repo: Path, commit: str, path: str) -> str:
    """Resolve the workflow blob only through the foundation's closed Git authority boundary.

    `foundation._git` pins `/usr/bin/git`, removes system/global config, disables replacement
    objects, restricts PATH, and rejects symlink/non-directory repository custody. Reusing that
    boundary prevents caller PATH, Git config, or refs/replace state from manufacturing the trusted
    workflow blob identity.
    """
    try:
        return foundation._git(tooling_repo, "rev-parse", f"{commit}:{path}").strip().lower()
    except FinalGoError:
        raise
    except (OSError, RuntimeError) as error:
        raise FinalGoError(
            "trusted default-branch workflow Git blob is unavailable from tooling repository"
        ) from error


def _fresh_crosscheck_receipt(
    *,
    tooling_repo: Path,
    candidate_root: Path,
    expected_source_sha: str,
    supplied_receipt: Path,
) -> bytes:
    """Regenerate crosscheck authority and require the handoff copy to describe the same result."""
    try:
        fresh_raw, fresh_record = trusted_crosscheck.execute_trusted_crosscheck(
            tooling_repo=tooling_repo,
            candidate_dir=candidate_root,
            expected_source_sha=expected_source_sha,
        )
    except trusted_crosscheck.TrustedCrosscheckExecutionError as error:
        raise FinalGoError(str(error)) from error

    supplied_raw = foundation._regular(
        supplied_receipt,
        "supplied independent retained-candidate crosscheck receipt",
    )
    supplied_record = foundation._json_bytes(
        supplied_raw,
        "supplied independent retained-candidate crosscheck receipt",
    )
    if supplied_record != fresh_record:
        raise FinalGoError(
            "supplied independent crosscheck receipt disagrees with fresh pinned producer execution"
        )
    return fresh_raw


def build_final_go_record(
    *,
    candidate_root: Path,
    expected_source_sha: str,
    expected_pr_number: int,
    trusted_xcode_run_id: int,
    trusted_xcode_job_id: int,
    trusted_xcode_artifact_id: int,
    trusted_xcode_artifact_archive: Path,
    independent_crosscheck_receipt: Path,
    frozen_source_repo: Path,
    tooling_repo: Path,
    operator_attestation: Path,
    github_get_json: Callable[[str], tuple[bytes, dict[str, Any]]] = foundation._api_get_json,
    now_utc=None,
) -> dict[str, Any]:
    """Run the foundation with trusted Xcode and crosscheck authority composed outside candidate input."""

    def trusted_subject_adapter(
        *,
        source: str,
        expected_pr_number: int,
        run_id: int,
        job_id: int,
        artifact_id: int,
        artifact_archive_path: Path,
        github_get_json: Callable[[str], tuple[bytes, dict[str, Any]]],
    ) -> dict[str, Any]:
        try:
            return trusted_xcode.verify_trusted_capture_xcode_subject(
                source_commit_sha=source,
                expected_pr_number=expected_pr_number,
                run_id=run_id,
                job_id=job_id,
                artifact_id=artifact_id,
                artifact_archive_path=artifact_archive_path,
                github_get_json=github_get_json,
                workflow_blob_sha_at_commit=lambda commit, path: _workflow_blob_sha_at_commit(
                    tooling_repo, commit, path
                ),
            )
        except trusted_xcode.TrustedCaptureXcodeError as error:
            raise FinalGoError(str(error)) from error

    fresh_crosscheck = _fresh_crosscheck_receipt(
        tooling_repo=tooling_repo,
        candidate_root=candidate_root,
        expected_source_sha=expected_source_sha,
        supplied_receipt=independent_crosscheck_receipt,
    )

    original = foundation._trusted_xcode_subject
    foundation._trusted_xcode_subject = trusted_subject_adapter
    try:
        with tempfile.TemporaryDirectory(prefix="nembra-final-go-crosscheck-authority-") as temporary:
            private_root = Path(temporary)
            private_root.chmod(0o700)
            trusted_receipt = private_root / "NembraTrustedCrosscheckReceipt.json"
            with trusted_receipt.open("xb") as handle:
                handle.write(fresh_crosscheck)
                handle.flush()
            trusted_receipt.chmod(0o600)
            if foundation._regular(trusted_receipt, "fresh trusted crosscheck receipt") != fresh_crosscheck:
                raise FinalGoError("fresh trusted crosscheck receipt bytes changed before foundation use")

            record = foundation.build_final_go_record(
                candidate_root=candidate_root,
                expected_source_sha=expected_source_sha,
                expected_pr_number=expected_pr_number,
                trusted_xcode_run_id=trusted_xcode_run_id,
                trusted_xcode_job_id=trusted_xcode_job_id,
                trusted_xcode_artifact_id=trusted_xcode_artifact_id,
                trusted_xcode_artifact_archive=trusted_xcode_artifact_archive,
                independent_crosscheck_receipt=trusted_receipt,
                frozen_source_repo=frozen_source_repo,
                tooling_repo=tooling_repo,
                operator_attestation=operator_attestation,
                github_get_json=github_get_json,
                now_utc=now_utc,
            )
    finally:
        foundation._trusted_xcode_subject = original

    subject = record.get("trustedXcodeAcceptance")
    if not isinstance(subject, dict):
        raise FinalGoError("hardened Final GO record lacks trusted Xcode acceptance subject")
    if subject.get("authority") != "default-branch-owner-command-v1":
        raise FinalGoError("hardened Final GO record did not consume default-branch Xcode authority")
    if subject.get("candidateSourceCommitSHA") != record.get("acceptedSourceCommitSHA"):
        raise FinalGoError("hardened Xcode subject candidate source diverged from accepted source")
    if subject.get("workflowSourceCommitSHA") == subject.get("candidateSourceCommitSHA"):
        raise FinalGoError("trusted workflow source must remain independent from candidate source")
    return record


def publish_record_no_replace(output_path: Path, raw: bytes) -> str:
    try:
        return publication.publish_record_no_replace(output_path, raw)
    except publication.FinalGoPublicationError as error:
        raise FinalGoError(str(error)) from error


def main(argv: list[str] | None = None) -> int:
    args = foundation._args(sys.argv[1:] if argv is None else argv)
    values = vars(args).copy()
    output = values.pop("output")
    try:
        record = build_final_go_record(**values)
        raw = (json.dumps(record, indent=2, sort_keys=True) + "\n").encode()
        record_sha = publish_record_no_replace(output, raw)
    except (FinalGoError, FileNotFoundError, OSError) as error:
        print(f"TODAY Final GO: NO-GO: {error}", file=sys.stderr)
        return 2
    print(f"TODAY Final GO record: {output.resolve(strict=True)}")
    print(f"record_sha256={record_sha}")
    print("PHYSICAL RESULT COLLECTED: NO")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
