#!/usr/bin/env python3
from pathlib import Path

HELPER = Path("scripts/ci/capture_selected_xcode_build_orchestrator.py")
TEST = Path("scripts/ci/tests/test_capture_accepted_root_build_composition.py")

source = HELPER.read_text(encoding="utf-8")
marker = '''    return rebased\n\n\ndef _replace_live_guard'''
insert = '''    return rebased\n\n\ndef _rebase_accepted_root_compiler_paths(\n    command: Sequence[str], *, live_repo: Path, accepted_root: Path\n) -> list[str]:\n    live_repo = _absolute_lexical(live_repo)\n    accepted_root = _absolute_lexical(accepted_root)\n    _require_real_directory(accepted_root, "accepted build root")\n\n    separators = [index for index, value in enumerate(command) if value == "--"]\n    if len(separators) != 1:\n        raise SelectedXcodeBuildOrchestratorError(\n            "strict accepted-root build requires exactly one compiler separator"\n        )\n    compiler_start = separators[0] + 1\n    compiler = list(command[compiler_start:])\n    workspace_matches = [index for index, value in enumerate(compiler) if value == "-workspace"]\n    project_matches = [index for index, value in enumerate(compiler) if value == "-project"]\n    if project_matches:\n        raise SelectedXcodeBuildOrchestratorError(\n            "strict accepted-root build does not admit project-path compiler authority"\n        )\n    if len(workspace_matches) != 1 or workspace_matches[0] + 1 >= len(compiler):\n        raise SelectedXcodeBuildOrchestratorError(\n            "strict accepted-root build requires exactly one workspace path"\n        )\n\n    workspace_index = compiler_start + workspace_matches[0] + 1\n    supplied = Path(command[workspace_index])\n    canonical_live = live_repo / "NembraCapture.xcworkspace"\n    if supplied.is_absolute():\n        if _absolute_lexical(supplied) != canonical_live:\n            raise SelectedXcodeBuildOrchestratorError(\n                "strict accepted-root workspace escaped the canonical live subject"\n            )\n    elif supplied != Path("NembraCapture.xcworkspace"):\n        raise SelectedXcodeBuildOrchestratorError(\n            "strict accepted-root workspace must be the canonical Capture workspace"\n        )\n\n    rebased = list(command)\n    rebased[workspace_index] = str(accepted_root / "NembraCapture.xcworkspace")\n    return rebased\n\n\ndef _replace_live_guard'''
if source.count(marker) != 1:
    raise SystemExit("expected one accepted-root compiler helper insertion seam")
source = source.replace(marker, insert)
old = '''            canonical_command = _rebase_private_guard_paths(\n                canonical_command, live_repo=repo, accepted_root=accepted_root\n            )\n            private_subjects = (\n'''
new = '''            canonical_command = _rebase_private_guard_paths(\n                canonical_command, live_repo=repo, accepted_root=accepted_root\n            )\n            canonical_command = _rebase_accepted_root_compiler_paths(\n                canonical_command, live_repo=repo, accepted_root=accepted_root\n            )\n            private_subjects = (\n'''
if source.count(old) != 1:
    raise SystemExit("expected one strict accepted-root command rebase seam")
HELPER.write_text(source.replace(old, new), encoding="utf-8")

source = TEST.read_text(encoding="utf-8")
old_command = '''        "--",\n        "/usr/bin/xcodebuild",\n        "-version",\n    ]\n'''
new_command = '''        "--",\n        "/usr/bin/xcodebuild",\n        "-workspace",\n        str(repo / "NembraCapture.xcworkspace"),\n        "-scheme",\n        "Nembra Capture",\n    ]\n'''
if source.count(old_command) != 1:
    raise SystemExit("expected one strict composition command fixture")
source = source.replace(old_command, new_command)
assertion_marker = '''            for flag, relative in expected.items():\n                self.assertEqual(\n                    rebased[rebased.index(flag) + 1],\n                    str(accepted_root / relative),\n                )\n            self.assertEqual(command, canonical_command(helper, REPOSITORY))\n\n            escaped = list(command)\n'''
assertion_replacement = '''            for flag, relative in expected.items():\n                self.assertEqual(\n                    rebased[rebased.index(flag) + 1],\n                    str(accepted_root / relative),\n                )\n            self.assertEqual(command, canonical_command(helper, REPOSITORY))\n\n            compiler_rebased = helper._rebase_accepted_root_compiler_paths(\n                rebased, live_repo=REPOSITORY, accepted_root=accepted_root\n            )\n            workspace_index = compiler_rebased.index("-workspace")\n            self.assertEqual(\n                compiler_rebased[workspace_index + 1],\n                str(accepted_root / "NembraCapture.xcworkspace"),\n            )\n\n            relative_workspace = list(rebased)\n            relative_workspace[relative_workspace.index("-workspace") + 1] = "NembraCapture.xcworkspace"\n            relative_rebased = helper._rebase_accepted_root_compiler_paths(\n                relative_workspace, live_repo=REPOSITORY, accepted_root=accepted_root\n            )\n            self.assertEqual(\n                relative_rebased[relative_rebased.index("-workspace") + 1],\n                str(accepted_root / "NembraCapture.xcworkspace"),\n            )\n\n            escaped_workspace = list(rebased)\n            escaped_workspace[escaped_workspace.index("-workspace") + 1] = str(REPOSITORY.parent / "attacker.xcworkspace")\n            with self.assertRaises(helper.SelectedXcodeBuildOrchestratorError):\n                helper._rebase_accepted_root_compiler_paths(\n                    escaped_workspace, live_repo=REPOSITORY, accepted_root=accepted_root\n                )\n\n            project_command = list(rebased)\n            project_command[project_command.index("-workspace")] = "-project"\n            with self.assertRaises(helper.SelectedXcodeBuildOrchestratorError):\n                helper._rebase_accepted_root_compiler_paths(\n                    project_command, live_repo=REPOSITORY, accepted_root=accepted_root\n                )\n\n            escaped = list(command)\n'''
if source.count(assertion_marker) != 1:
    raise SystemExit("expected one accepted-root fixture assertion seam")
source = source.replace(assertion_marker, assertion_replacement)
build_assert = '''    assert _value(command, "--identity-sources") == EXPECTED_ROOT + "/LocalSecrets/TuyaRuntime/Sources/NembraTuyaPrivateConfig"\n    developer = "/Library/NembraSelectedXcodeFreeze.fixture/Xcode.app/Contents/Developer"\n'''
build_replace = '''    assert _value(command, "--identity-sources") == EXPECTED_ROOT + "/LocalSecrets/TuyaRuntime/Sources/NembraTuyaPrivateConfig"\n    assert _value(command, "-workspace") == EXPECTED_ROOT + "/NembraCapture.xcworkspace"\n    developer = "/Library/NembraSelectedXcodeFreeze.fixture/Xcode.app/Contents/Developer"\n'''
if source.count(build_assert) != 1:
    raise SystemExit("expected one strict compiler build assertion seam")
TEST.write_text(source.replace(build_assert, build_replace), encoding="utf-8")
