import Foundation
import Testing

@Test("Home machine hero and recovery surfaces reflow at Accessibility Dynamic Type")
func homeMachineHeroAndRecoveryReflowAtAccessibilityDynamicType() throws {
    let sourceURL = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .appendingPathComponent("NembraApp/Features/Home/HomeView.swift")
    let source = try String(contentsOf: sourceURL, encoding: .utf8)

    #expect(source.contains("@Environment(\\.dynamicTypeSize) private var dynamicTypeSize"))
    #expect(source.contains("@Environment(\\.accessibilityReduceMotion) private var reduceMotion"))
    #expect(source.contains("@Environment(\\.accessibilityReduceTransparency) private var reduceTransparency"))
    #expect(source.contains("home.machine-hero"))
    #expect(source.contains("home.machine-readiness"))
    #expect(source.contains("home.metric.battery"))
    #expect(source.contains("home.metric.trip"))
    #expect(source.contains("home.metric.mode"))
    #expect(source.contains("batteryAccessibilityValue"))
    #expect(source.contains("percent, low battery"))
    #expect(!source.contains("private var statusPanel: some View"))

    let heroStart = try #require(source.range(of: "private var machineHero: some View"))
    let controlsStart = try #require(source.range(of: "private var controlsSection: some View", range: heroStart.upperBound..<source.endIndex))
    let hero = String(source[heroStart.lowerBound..<controlsStart.lowerBound])

    #expect(hero.contains("if dynamicTypeSize.isAccessibilitySize"))
    #expect(hero.contains("VStack(alignment: .leading, spacing: 18)"))
    #expect(hero.contains("batteryInstrument"))
    #expect(hero.contains("heroContextMetrics"))
    #expect(hero.contains("machineReadinessStrip"))
    #expect(hero.contains("LAST KNOWN"))
    #expect(hero.contains("LIVE"))
    #expect(hero.contains("WAITING"))
    #expect(hero.contains("reduceMotion ? .identity : .numericText()"))
    #expect(hero.contains(".lineLimit(dynamicTypeSize.isAccessibilitySize ? nil : 1)"))
    #expect(hero.contains(".minimumScaleFactor(dynamicTypeSize.isAccessibilitySize ? 1 : 0.72)"))

    let headerStart = try #require(source.range(of: "private var vehicleHeader: some View"))
    let panelStart = try #require(source.range(of: "private var machineHero: some View", range: headerStart.upperBound..<source.endIndex))
    let header = String(source[headerStart.lowerBound..<panelStart.lowerBound])
    #expect(header.contains("if dynamicTypeSize.isAccessibilitySize"))
    #expect(header.contains("VStack(alignment: .leading, spacing: 12)"))

    let recoveryStart = try #require(source.range(of: "private var connectionRecovery: some View"))
    let recoveryEnd = try #require(source.range(of: "private enum ConnectionRecoveryAction", range: recoveryStart.upperBound..<source.endIndex))
    let recovery = String(source[recoveryStart.lowerBound..<recoveryEnd.lowerBound])
    #expect(recovery.contains("if dynamicTypeSize.isAccessibilitySize"))
    #expect(recovery.contains(".frame(minWidth: 44, minHeight: 44)"))
    #expect(recovery.contains(".accessibilityHidden(true)"))
}
