#!/usr/bin/env python3
"""Fingerprint and optionally guard the generated CocoaPods build subject.

The accepted Podfile.lock proves dependency resolution, but xcodebuild consumes generated
workspace/support bytes too. This helper binds those generated bytes without serializing
private source contents: only a canonical SHA-256 subject digest leaves the local checkout.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import select
import stat
import subprocess
import sys
from pathlib import Path
from typing import Iterable, Sequence

SCHEMA = b"nembra-cocoapods-generated-build-subject-v1"


class SubjectError(RuntimeError):
    pass


def _feed(digest: "hashlib._Hash", value: bytes) -> None:
    digest.update(len(value).to_bytes(8, "big"))
    digest.update(value)


def _identity(metadata: os.stat_result) -> tuple[int, ...]:
    return (
        metadata.st_dev,
        metadata.st_ino,
        metadata.st_mode,
        metadata.st_uid,
        metadata.st_gid,
        metadata.st_size,
        metadata.st_mtime_ns,
        metadata.st_ctime_ns,
    )


def _stable_file_digest(path: Path, expected: tuple[int, ...]) -> bytes:
    nofollow = getattr(os, "O_NOFOLLOW", None)
    if nofollow is None:
        raise SubjectError("generated-build subject admission requires O_NOFOLLOW support")
    flags = os.O_RDONLY | nofollow | getattr(os, "O_CLOEXEC", 0)
    try:
        descriptor = os.open(path, flags)
    except OSError as error:
        raise SubjectError(f"generated build file could not be opened safely: {path}") from error
    try:
        before = os.fstat(descriptor)
        if _identity(before) != expected or not stat.S_ISREG(before.st_mode):
            raise SubjectError(f"generated build file changed before hashing: {path}")
        digest = hashlib.sha256()
        count = 0
        while True:
            chunk = os.read(descriptor, 1024 * 1024)
            if not chunk:
                break
            count += len(chunk)
            digest.update(chunk)
        after = os.fstat(descriptor)
        if _identity(after) != expected or count != after.st_size:
            raise SubjectError(f"generated build file changed while hashing: {path}")
        final = path.lstat()
        if _identity(final) != expected or stat.S_ISLNK(final.st_mode):
            raise SubjectError(f"generated build pathname changed during hashing: {path}")
        return digest.digest()
    finally:
        os.close(descriptor)


def _directory_members(path: Path) -> tuple[str, ...]:
    try:
        return tuple(sorted(os.listdir(path), key=os.fsencode))
    except OSError as error:
        raise SubjectError(f"generated build directory changed during hashing: {path}") from error


def _tree_manifest(root: Path) -> tuple[tuple[str, str, int, bytes], ...]:
    try:
        root_metadata = root.lstat()
    except OSError as error:
        raise SubjectError(f"required generated build directory is unavailable: {root}") from error
    if stat.S_ISLNK(root_metadata.st_mode) or not stat.S_ISDIR(root_metadata.st_mode):
        raise SubjectError(f"required generated build directory is not a real directory: {root}")

    observed: list[tuple[Path, tuple[int, ...], str]] = [
        (root, _identity(root_metadata), "D")
    ]
    memberships: dict[Path, tuple[str, ...]] = {}
    entries: list[tuple[str, str, int, bytes]] = [
        ("D", ".", stat.S_IMODE(root_metadata.st_mode), b"")
    ]

    for current_text, directory_names, file_names in os.walk(root, topdown=True, followlinks=False):
        current = Path(current_text)
        memberships[current] = tuple(sorted((*directory_names, *file_names), key=os.fsencode))
        kept_directories: list[str] = []

        for name in sorted(directory_names, key=os.fsencode):
            path = current / name
            relative = path.relative_to(root).as_posix()
            metadata = path.lstat()
            identity = _identity(metadata)
            mode = stat.S_IMODE(metadata.st_mode)
            if stat.S_ISLNK(metadata.st_mode):
                target_before = os.readlink(path)
                target_after = os.readlink(path)
                if target_before != target_after or _identity(path.lstat()) != identity:
                    raise SubjectError(f"generated build symlink changed while hashing: {path}")
                observed.append((path, identity, "L"))
                entries.append(("L", relative, mode, os.fsencode(target_before)))
            elif stat.S_ISDIR(metadata.st_mode):
                observed.append((path, identity, "D"))
                entries.append(("D", relative, mode, b""))
                kept_directories.append(name)
            else:
                raise SubjectError(f"generated build tree contains unsupported directory entry: {path}")
        directory_names[:] = kept_directories

        for name in sorted(file_names, key=os.fsencode):
            path = current / name
            relative = path.relative_to(root).as_posix()
            metadata = path.lstat()
            identity = _identity(metadata)
            mode = stat.S_IMODE(metadata.st_mode)
            if stat.S_ISLNK(metadata.st_mode):
                target_before = os.readlink(path)
                target_after = os.readlink(path)
                if target_before != target_after or _identity(path.lstat()) != identity:
                    raise SubjectError(f"generated build symlink changed while hashing: {path}")
                observed.append((path, identity, "L"))
                entries.append(("L", relative, mode, os.fsencode(target_before)))
            elif stat.S_ISREG(metadata.st_mode):
                payload = _stable_file_digest(path, identity)
                observed.append((path, identity, "F"))
                entries.append(("F", relative, mode, payload))
            else:
                raise SubjectError(f"generated build tree contains unsupported file entry: {path}")

    for path, expected, kind in observed:
        metadata = path.lstat()
        if _identity(metadata) != expected:
            raise SubjectError(f"generated build tree changed during final custody: {path}")
        if kind == "D" and not stat.S_ISDIR(metadata.st_mode):
            raise SubjectError(f"generated build directory changed type: {path}")
        if kind == "F" and not stat.S_ISREG(metadata.st_mode):
            raise SubjectError(f"generated build file changed type: {path}")
        if kind == "L" and not stat.S_ISLNK(metadata.st_mode):
            raise SubjectError(f"generated build symlink changed type: {path}")
    for directory, expected_members in memberships.items():
        if _directory_members(directory) != expected_members:
            raise SubjectError(f"generated build directory membership changed: {directory}")

    return tuple(sorted(entries, key=lambda item: os.fsencode(item[1])))


def _tree_digest(root: Path, label: bytes) -> bytes:
    digest = hashlib.sha256()
    _feed(digest, b"nembra-generated-tree-v1")
    _feed(digest, label)
    for kind, relative, mode, payload in _tree_manifest(root):
        _feed(digest, kind.encode("ascii"))
        _feed(digest, os.fsencode(relative))
        _feed(digest, mode.to_bytes(4, "big"))
        _feed(digest, payload)
    return digest.digest()


def fingerprint_subject(pods: Path, workspace: Path) -> str:
    digest = hashlib.sha256()
    _feed(digest, SCHEMA)
    _feed(digest, _tree_digest(pods, b"Pods"))
    _feed(digest, _tree_digest(workspace, b"NembraCapture.xcworkspace"))
    return digest.hexdigest()


def _watch_paths(roots: Iterable[Path]) -> tuple[Path, ...]:
    paths: set[Path] = set()
    for root in roots:
        metadata = root.lstat()
        if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
            raise SubjectError(f"generated build guard root is not a real directory: {root}")
        paths.add(root)
        for current_text, directory_names, file_names in os.walk(root, topdown=True, followlinks=False):
            current = Path(current_text)
            paths.add(current)
            for name in directory_names:
                candidate = current / name
                if not candidate.is_symlink():
                    paths.add(candidate)
            for name in file_names:
                candidate = current / name
                if not candidate.is_symlink():
                    paths.add(candidate)
    return tuple(sorted(paths, key=lambda item: str(item)))


def _run_guarded(pods: Path, workspace: Path, command: Sequence[str]) -> int:
    if not command:
        raise SubjectError("generated build guard requires one child command")
    required = (
        "kqueue", "kevent", "KQ_FILTER_VNODE", "KQ_EV_ADD", "KQ_EV_ENABLE", "KQ_EV_CLEAR",
        "KQ_NOTE_DELETE", "KQ_NOTE_WRITE", "KQ_NOTE_EXTEND", "KQ_NOTE_LINK", "KQ_NOTE_RENAME", "KQ_NOTE_REVOKE",
    )
    missing = [name for name in required if not hasattr(select, name)]
    if missing:
        raise SubjectError("generated build guard requires macOS kqueue vnode monitoring")

    initial = fingerprint_subject(pods, workspace)
    queue = select.kqueue()
    opened: list[tuple[int, Path]] = []
    process: subprocess.Popen | None = None
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    fflags = (
        select.KQ_NOTE_DELETE | select.KQ_NOTE_WRITE | select.KQ_NOTE_EXTEND |
        select.KQ_NOTE_LINK | select.KQ_NOTE_RENAME | select.KQ_NOTE_REVOKE
    )
    try:
        for path in _watch_paths((pods, workspace)):
            before = _identity(path.lstat())
            descriptor = os.open(path, flags)
            after = _identity(os.fstat(descriptor))
            if before != after:
                os.close(descriptor)
                raise SubjectError(f"generated build subject changed while guard was armed: {path}")
            queue.control([
                select.kevent(
                    descriptor,
                    filter=select.KQ_FILTER_VNODE,
                    flags=select.KQ_EV_ADD | select.KQ_EV_ENABLE | select.KQ_EV_CLEAR,
                    fflags=fflags,
                )
            ], 0, 0)
            opened.append((descriptor, path))

        if fingerprint_subject(pods, workspace) != initial or queue.control(None, 256, 0):
            raise SubjectError("generated build subject changed before xcodebuild admission")

        process = subprocess.Popen(list(command))
        while process.poll() is None:
            events = queue.control(None, 256, 0.10)
            if events:
                process.terminate()
                try:
                    process.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait(timeout=5)
                raise SubjectError("generated CocoaPods build subject changed while xcodebuild was running")

        if queue.control(None, 256, 0):
            raise SubjectError("generated CocoaPods build subject changed at xcodebuild completion")
        if fingerprint_subject(pods, workspace) != initial:
            raise SubjectError("generated CocoaPods build subject changed across xcodebuild")
        if queue.control(None, 256, 0):
            raise SubjectError("generated CocoaPods build subject changed during final verification")
        return int(process.returncode or 0)
    finally:
        if process is not None and process.poll() is None:
            process.terminate()
            try:
                process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait(timeout=5)
        for descriptor, _ in opened:
            try:
                os.close(descriptor)
            except OSError:
                pass
        queue.close()


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Bind the generated CocoaPods build subject used by Nembra Capture.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    fingerprint = subparsers.add_parser("fingerprint")
    fingerprint.add_argument("--pods", required=True, type=Path)
    fingerprint.add_argument("--workspace", required=True, type=Path)

    guard = subparsers.add_parser("guard")
    guard.add_argument("--pods", required=True, type=Path)
    guard.add_argument("--workspace", required=True, type=Path)
    guard.add_argument("child", nargs=argparse.REMAINDER)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(sys.argv[1:] if argv is None else argv)
    try:
        if args.command == "fingerprint":
            print(fingerprint_subject(args.pods, args.workspace))
            return 0
        child = list(args.child)
        if child and child[0] == "--":
            child = child[1:]
        return _run_guarded(args.pods, args.workspace, child)
    except (OSError, SubjectError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 74


if __name__ == "__main__":
    raise SystemExit(main())
