#!/usr/bin/env python3
"""Fingerprint the exact generated CocoaPods build subject consumed by Capture.

`Podfile.lock` proves dependency resolution, not the generated workspace/support
bytes consumed by xcodebuild. This helper binds those generated bytes while
allowing only explicitly declared external symlink roots that are independently
fingerprinted and guarded by the private Tuya custody layer.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import stat
import sys
from pathlib import Path
from typing import Iterable, Sequence

SCHEMA = b"nembra-cocoapods-generated-build-subject-v2"


class SubjectError(RuntimeError):
    pass


def _feed(digest: "hashlib._Hash", value: bytes) -> None:
    digest.update(len(value).to_bytes(8, "big"))
    digest.update(value)


def _identity(metadata: os.stat_result) -> tuple[int, ...]:
    return (
        metadata.st_dev,
        metadata.st_ino,
        metadata.st_mode,
        metadata.st_uid,
        metadata.st_gid,
        metadata.st_size,
        metadata.st_mtime_ns,
        metadata.st_ctime_ns,
    )


def _stable_file_digest(path: Path, expected: tuple[int, ...]) -> bytes:
    nofollow = getattr(os, "O_NOFOLLOW", None)
    if nofollow is None:
        raise SubjectError("generated-build subject admission requires O_NOFOLLOW support")
    flags = os.O_RDONLY | nofollow | getattr(os, "O_CLOEXEC", 0)
    try:
        descriptor = os.open(path, flags)
    except OSError as error:
        raise SubjectError(f"generated build file could not be opened safely: {path}") from error
    try:
        before = os.fstat(descriptor)
        if _identity(before) != expected or not stat.S_ISREG(before.st_mode):
            raise SubjectError(f"generated build file changed before hashing: {path}")
        digest = hashlib.sha256()
        count = 0
        while True:
            chunk = os.read(descriptor, 1024 * 1024)
            if not chunk:
                break
            count += len(chunk)
            digest.update(chunk)
        after = os.fstat(descriptor)
        if _identity(after) != expected or count != after.st_size:
            raise SubjectError(f"generated build file changed while hashing: {path}")
        current = path.lstat()
        if _identity(current) != expected or stat.S_ISLNK(current.st_mode):
            raise SubjectError(f"generated build pathname changed during hashing: {path}")
        return digest.digest()
    finally:
        os.close(descriptor)


def _directory_members(path: Path) -> tuple[str, ...]:
    try:
        return tuple(sorted(os.listdir(path), key=os.fsencode))
    except OSError as error:
        raise SubjectError(f"generated build directory changed during hashing: {path}") from error


def _real_directory(path: Path, label: str) -> Path:
    try:
        metadata = path.lstat()
        resolved = path.resolve(strict=True)
    except OSError as error:
        raise SubjectError(f"required {label} directory is unavailable: {path}") from error
    if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
        raise SubjectError(f"required {label} directory is not one real directory: {path}")
    return resolved


def _contains(root: Path, candidate: Path) -> bool:
    return candidate == root or root in candidate.parents


def _stable_symlink_target(path: Path, expected: tuple[int, ...], allowed_roots: tuple[Path, ...]) -> bytes:
    try:
        target_before = os.readlink(path)
        resolved = path.resolve(strict=True)
        target_after = os.readlink(path)
        final = path.lstat()
    except OSError as error:
        raise SubjectError(f"generated build symlink is broken or unstable: {path}") from error
    if target_before != target_after or _identity(final) != expected or not stat.S_ISLNK(final.st_mode):
        raise SubjectError(f"generated build symlink changed while hashing: {path}")
    if not any(_contains(root, resolved) for root in allowed_roots):
        raise SubjectError(
            f"generated build symlink escapes the generated subject and separately guarded private roots: {path}"
        )
    return os.fsencode(target_before)


def _tree_manifest(root: Path, allowed_roots: tuple[Path, ...]) -> tuple[tuple[str, str, int, bytes], ...]:
    root_resolved = _real_directory(root, "generated build")
    root_metadata = root.lstat()
    observed: list[tuple[Path, tuple[int, ...], str]] = [
        (root, _identity(root_metadata), "D")
    ]
    memberships: dict[Path, tuple[str, ...]] = {}
    entries: list[tuple[str, str, int, bytes]] = [
        ("D", ".", stat.S_IMODE(root_metadata.st_mode), b"")
    ]

    if root_resolved not in allowed_roots:
        raise SubjectError("generated subject root is missing from its own allowed-root set")

    for current_text, directory_names, file_names in os.walk(root, topdown=True, followlinks=False):
        current = Path(current_text)
        memberships[current] = tuple(sorted((*directory_names, *file_names), key=os.fsencode))
        kept_directories: list[str] = []

        for name in sorted(directory_names, key=os.fsencode):
            path = current / name
            relative = path.relative_to(root).as_posix()
            metadata = path.lstat()
            identity = _identity(metadata)
            mode = stat.S_IMODE(metadata.st_mode)
            if stat.S_ISLNK(metadata.st_mode):
                payload = _stable_symlink_target(path, identity, allowed_roots)
                observed.append((path, identity, "L"))
                entries.append(("L", relative, mode, payload))
            elif stat.S_ISDIR(metadata.st_mode):
                observed.append((path, identity, "D"))
                entries.append(("D", relative, mode, b""))
                kept_directories.append(name)
            else:
                raise SubjectError(f"generated build tree contains unsupported directory entry: {path}")
        directory_names[:] = kept_directories

        for name in sorted(file_names, key=os.fsencode):
            path = current / name
            relative = path.relative_to(root).as_posix()
            metadata = path.lstat()
            identity = _identity(metadata)
            mode = stat.S_IMODE(metadata.st_mode)
            if stat.S_ISLNK(metadata.st_mode):
                payload = _stable_symlink_target(path, identity, allowed_roots)
                observed.append((path, identity, "L"))
                entries.append(("L", relative, mode, payload))
            elif stat.S_ISREG(metadata.st_mode):
                payload = _stable_file_digest(path, identity)
                observed.append((path, identity, "F"))
                entries.append(("F", relative, mode, payload))
            else:
                raise SubjectError(f"generated build tree contains unsupported file entry: {path}")

    for path, expected, kind in observed:
        try:
            metadata = path.lstat()
        except OSError as error:
            raise SubjectError(f"generated build tree changed during final custody: {path}") from error
        if _identity(metadata) != expected:
            raise SubjectError(f"generated build tree changed during final custody: {path}")
        if kind == "D" and not stat.S_ISDIR(metadata.st_mode):
            raise SubjectError(f"generated build directory changed type: {path}")
        if kind == "F" and not stat.S_ISREG(metadata.st_mode):
            raise SubjectError(f"generated build file changed type: {path}")
        if kind == "L" and not stat.S_ISLNK(metadata.st_mode):
            raise SubjectError(f"generated build symlink changed type: {path}")
    for directory, expected_members in memberships.items():
        if _directory_members(directory) != expected_members:
            raise SubjectError(f"generated build directory membership changed: {directory}")

    return tuple(sorted(entries, key=lambda item: os.fsencode(item[1])))


def _tree_digest(root: Path, label: bytes, allowed_roots: tuple[Path, ...]) -> bytes:
    digest = hashlib.sha256()
    _feed(digest, b"nembra-generated-tree-v2")
    _feed(digest, label)
    for kind, relative, mode, payload in _tree_manifest(root, allowed_roots):
        _feed(digest, kind.encode("ascii"))
        _feed(digest, os.fsencode(relative))
        _feed(digest, mode.to_bytes(4, "big"))
        _feed(digest, payload)
    return digest.digest()


def fingerprint_subject(
    pods: Path,
    workspace: Path,
    *,
    separately_guarded_external_roots: Iterable[Path] = (),
) -> str:
    pods_root = _real_directory(pods, "Pods")
    workspace_root = _real_directory(workspace, "workspace")
    external_roots = tuple(
        _real_directory(path, "separately guarded external")
        for path in separately_guarded_external_roots
    )
    allowed_roots = (pods_root, workspace_root, *external_roots)

    digest = hashlib.sha256()
    _feed(digest, SCHEMA)
    _feed(digest, _tree_digest(pods, b"Pods", allowed_roots))
    _feed(digest, _tree_digest(workspace, b"NembraCapture.xcworkspace", allowed_roots))
    return digest.hexdigest()


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Bind the generated CocoaPods build subject used by Nembra Capture."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)
    fingerprint = subparsers.add_parser("fingerprint")
    fingerprint.add_argument("--pods", required=True, type=Path)
    fingerprint.add_argument("--workspace", required=True, type=Path)
    fingerprint.add_argument(
        "--separately-guarded-external-root",
        action="append",
        default=[],
        type=Path,
        help="External symlink root whose bytes are independently proven and guarded by the caller.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(sys.argv[1:] if argv is None else argv)
    try:
        print(
            fingerprint_subject(
                args.pods,
                args.workspace,
                separately_guarded_external_roots=args.separately_guarded_external_root,
            )
        )
        return 0
    except (OSError, SubjectError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 74


if __name__ == "__main__":
    raise SystemExit(main())
