#!/usr/bin/env python3
"""Fingerprint the exact CocoaPods-generated build subject used by Nembra Capture.

The reviewed Podfile.lock identifies dependency resolution, but it does not identify
the generated workspace/support files that xcodebuild actually consumes. This helper
binds those ignored generated bytes as a separate deterministic SHA-256 subject.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
from pathlib import Path
from typing import Sequence


class GeneratedSubjectError(RuntimeError):
    pass


def _load_provenance_module():
    helper = Path(__file__).with_name("capture_tuya_private_input_provenance.py")
    spec = importlib.util.spec_from_file_location(
        "capture_tuya_private_input_provenance", helper
    )
    if spec is None or spec.loader is None:
        raise GeneratedSubjectError("private-input provenance helper could not be loaded")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


provenance = _load_provenance_module()


def _feed(digest: "hashlib._Hash", value: bytes) -> None:
    digest.update(len(value).to_bytes(8, "big"))
    digest.update(value)


def generated_subject_sha256(*, pods: Path, workspace: Path) -> str:
    """Return one domain-separated digest for the exact generated build graph."""
    try:
        pods_fingerprint = provenance._tree_fingerprint(pods)
        workspace_fingerprint = provenance._tree_fingerprint(workspace)
    except provenance.ProvenanceError as error:
        raise GeneratedSubjectError(
            f"CocoaPods generated build subject is unavailable or unsafe: {error}"
        ) from error

    digest = hashlib.sha256()
    _feed(digest, b"nembra-cocoapods-generated-build-subject-v1")
    _feed(digest, b"Pods")
    _feed(digest, bytes.fromhex(pods_fingerprint))
    _feed(digest, b"NembraCapture.xcworkspace")
    _feed(digest, bytes.fromhex(workspace_fingerprint))
    return digest.hexdigest()


def _parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fingerprint exact CocoaPods-generated Nembra Capture build inputs."
    )
    parser.add_argument("--pods", required=True, type=Path)
    parser.add_argument("--workspace", required=True, type=Path)
    return parser.parse_args(list(argv))


def main(argv: Sequence[str] | None = None) -> int:
    import sys

    args = _parse_args(sys.argv[1:] if argv is None else argv)
    try:
        value = generated_subject_sha256(pods=args.pods, workspace=args.workspace)
    except GeneratedSubjectError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 76
    print(value)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
